name: Build CI

on:
  push:
    branches: [ main ]

env:
  WARN_ON_PR: "artifact upload is disabled due to the workflow is trigged by pull request."

jobs:
  gradle:
    name: Gradle CI Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Prepare Java 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        java-package: jdk+fx

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build project
      run: |
        if ${{ !!github.head_ref }}; then echo "::warning:: Gradle $WARN_ON_PR"; fi
        ./gradlew build

    - name: Get short SHA
      id: sha7
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

    - name: Upload Release package
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        path: app/build/outputs/apk/release
        name: Build-Release-${{ steps.sha7.outputs.sha }}

    - name: Upload Debug package
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        path: app/build/outputs/apk/debug
        name: Build-Debug-${{ steps.sha7.outputs.sha }}
